

url: "https://fgaudenz.github.io/kitesenkula"
baseurl: ""

title: "KITES'N KULA"
email: "info@kitesnkula.com"
description: "Kitesurf community — not a school, not a course. An attitude."
author: "Filippo Gaudenzi & Simone Giacomini"

locale: "en-US"


analytics:
  google: ""

collections:
  portfolio:

markdown: kramdown

languages: ["it", "en", "de", "fr"]
default_lang: it
lang: it
plugins:
  - jekyll-multiple-languages-plugin


exclude_from_localizations:
  - "assets/"
  - "css/"
  - "js/"
  - "images/"
  - "favicon.ico"